# Settings up the listening interface:
interface=eth0
bind-interfaces
listen-address=192.168.88.253

# Defining the basic settings of the DHCP server:
dhcp-range=192.168.88.201,192.168.88.250,255.255.255.0,12h

# Settings the default gateway for the DHCP server:
dhcp-option=3,192.168.88.254

# DNS server settings for DHCP:
dhcp-option=6,192.168.88.253

# Settings of remote DNS servers:
server=9.9.9.9
server=1.1.1.1

# Domain name requirement for all requests:
domain-needed
domain=local

# Blocking of private IP addresses in requests:
bogus-priv
